#
# Jenkins pipeline for CNaaS NAC
#

disabled: false

git:
  branch: develop
  extensions:
    shallow_clone: true

extra_jobs:
  - name: nac-authapi
    git:
      branch: develop
    builders:
      - docker
    pre_build_script:
      - cp docker/api/Dockerfile .
    docker_name: cnaas/nac-authapi
    docker_context_dir: .
    docker_tags:
      - "v2.0.0"

  - name: nac-radius
    git:
      branch: develop
    builders:
      - docker
    pre_build_script:
      - cp docker/radius/Dockerfile .
    docker_name: cnaas/nac-radius
    docker_context_dir: .
    docker_tags:
      - "v2.0.0"