dev_addr: '127.0.0.1:8008'
site_name: CNaaS NAC documentation
site_description: Documentation for CNaaS NAC
site_author: SUNET
site_url: 'https://cnaas-nac.readthedocs.io/en/latest/'
repo_url: 'https://github.com/SUNET/cnaas-nac'
repo_name: SUNET/cnaas-nac
copyright: 2026, SUNET
theme:
  variant: classic
  language: en
  hljs_languages:
    - python
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: lucide/sun-moon
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: lucide/sun
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: lucide/moon
        name: Switch to system preference

  features:
    - content.code.copy
    - content.code.select
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
watch:
  - docs
extra_css:
  - stylesheets/extra.css
nav:
  - Overview:
    - Overview: index.md
    - Links: links.md
  - User manual:
    - User manual: user_manual/index.md
    - Endpoints: user_manual/endpoints.md
    - Policies: user_manual/policies.md
    - API: user_manual/api.md
  - Configuration:
    - Configuration: configuration/index.md
    - Environment variables: configuration/environment_variables.md
    - Switch Example Configuration:
      - Arista: configuration/switch_example/arista.md
      - Cisco: configuration/switch_example/cisco.md
  - Development:
    - Development: development/index.md
    - Testing: development/testing.md
  - Changelog:
    - Changelog: changelog/index.md