dev_addr: '127.0.0.1:8008'
site_name: CNaaS NAC documentation
site_description: Documentation for CNaaS NAC
site_author: SUNET
site_url: 'https://cnaas-nac.readthedocs.io/en/latest/'
repo_url: 'https://github.com/SUNET/cnaas-nac'
theme:
  name: material
  hljs_languages:
    - python
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - content.code.copy
    - content.code.select
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
watch:
  - mkdocs.yml
  - docs
nav:
  - Overview:
    - Overview: index.md
    - Links: links.md
  - User manual:
    - User manual: user_manual/index.md
    - Endpoints: user_manual/endpoints.md
    - Policies: user_manual/policies.md
    - API: user_manual/api.md
  - Configuration:
    - Configuration: configuration.md
    - Environment variables: environment_variables.md
    - Switch Example Configuration:
      - Arista: switch_example_configuration/arista.md
      - Cisco: switch_example_configuration/cisco.md
  - Development:
    - Development: development.md
    - Testing: testing.md