"""nac tables

Revision ID: 8952cdf18498
Revises: 
Create Date: 2026-02-24 20:39:11.632593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8952cdf18498'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('target_vlan', sa.Integer(), nullable=False),
    sa.Column('match_logic', sa.Enum('ALL', 'ANY', name='matchlogic'), nullable=False),
    sa.Column('reevaluate_existing', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_assignment_rule_priority'), 'assignment_rule', ['priority'], unique=False)
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('allowed_vlans', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_id'), 'group', ['id'], unique=False)
    op.create_index(op.f('ix_group_name'), 'group', ['name'], unique=True)
    op.create_table('nasport',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.Unicode(length=64), nullable=False),
    sa.Column('nas_identifier', sa.Unicode(length=64), nullable=False),
    sa.Column('nas_port_id', sa.Unicode(length=64), nullable=False),
    sa.Column('nas_ip_address', sa.Unicode(length=64), nullable=False),
    sa.Column('calling_station_id', sa.Unicode(length=64), nullable=False),
    sa.Column('called_station_id', sa.Unicode(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username', 'calling_station_id', 'nas_port_id', name='uq_user_calling_station_port'),
    sa.UniqueConstraint('username', 'nas_identifier', 'nas_port_id', name='uq_user_nas_port')
    )
    op.create_index(op.f('ix_nasport_username'), 'nasport', ['username'], unique=False)
    op.create_table('radacct',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('acct_session_id', sa.Text(), nullable=False),
    sa.Column('acct_unique_id', sa.Text(), nullable=False),
    sa.Column('nas_ip_address', postgresql.INET(), nullable=False),
    sa.Column('nas_identifier', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('group_name', sa.Text(), nullable=True),
    sa.Column('realm', sa.Text(), nullable=True),
    sa.Column('nas_port_id', sa.Text(), nullable=True),
    sa.Column('nas_port_type', sa.Text(), nullable=True),
    sa.Column('acct_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acct_update_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acct_stop_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acct_interval', sa.BigInteger(), nullable=True),
    sa.Column('acct_session_time', sa.BigInteger(), nullable=True),
    sa.Column('acct_authentic', sa.Text(), nullable=True),
    sa.Column('connectinfo_start', sa.Text(), nullable=True),
    sa.Column('connectinfo_stop', sa.Text(), nullable=True),
    sa.Column('acct_input_octets', sa.BigInteger(), nullable=True),
    sa.Column('acct_output_octets', sa.BigInteger(), nullable=True),
    sa.Column('called_station_id', sa.Text(), nullable=True),
    sa.Column('calling_station_id', sa.Text(), nullable=True),
    sa.Column('acct_terminate_cause', sa.Text(), nullable=True),
    sa.Column('service_type', sa.Text(), nullable=True),
    sa.Column('framed_protocol', sa.Text(), nullable=True),
    sa.Column('framed_ip_address', postgresql.INET(), nullable=True),
    sa.Column('framed_ipv6_address', postgresql.INET(), nullable=True),
    sa.Column('framed_ipv6_prefix', postgresql.INET(), nullable=True),
    sa.Column('framed_interface_id', sa.Text(), nullable=True),
    sa.Column('delegated_ipv6_prefix', postgresql.INET(), nullable=True),
    sa.Column('class', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='radacct_pkey'),
    sa.UniqueConstraint('acct_unique_id', name='radacct_acct_unique_id_key')
    )
    op.create_index('radacct_active_session_idx', 'radacct', ['acct_unique_id'], unique=False)
    op.create_index('radacct_bulk_close', 'radacct', ['nas_ip_address', 'acct_start_time'], unique=False)
    op.create_index('radacct_bulk_timeout', 'radacct', [sa.literal_column('acct_stop_time NULLS FIRST'), 'acct_update_time'], unique=False)
    op.create_index('radacct_start_user_idx', 'radacct', ['acct_start_time', 'username'], unique=False)
    op.create_table('radpostauth',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('auth_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pass', sa.Text(), nullable=True),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('called_station_id', sa.Text(), nullable=True),
    sa.Column('calling_station_id', sa.Text(), nullable=True),
    sa.Column('reply_message', sa.Text(), nullable=True),
    sa.Column('nas_identifier', sa.Text(), nullable=True),
    sa.Column('nas_port_id', sa.Text(), nullable=True),
    sa.Column('class', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='radpostauth_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), server_default=sa.text("''::text"), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('vlan', sa.Integer(), nullable=False),
    sa.Column('access_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_stop', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('username', name='uq_username')
    )
    op.create_index('user_username', 'user', ['username'], unique=False)
    op.create_table('assignment_rule_condition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('attribute', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.Enum('EQUALS', 'NOT_EQUALS', 'CONTAINS', 'STARTS_WITH', 'ENDS_WITH', 'REGEX', 'IN_LIST', name='operator'), nullable=False),
    sa.Column('target_value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['assignment_rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('methods', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_permission_id'), 'group_permission', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_permission_id'), table_name='group_permission')
    op.drop_table('group_permission')
    op.drop_table('assignment_rule_condition')
    op.drop_index('user_username', table_name='user')
    op.drop_table('user')
    op.drop_table('radpostauth')
    op.drop_index('radacct_start_user_idx', table_name='radacct')
    op.drop_index('radacct_bulk_timeout', table_name='radacct')
    op.drop_index('radacct_bulk_close', table_name='radacct')
    op.drop_index('radacct_active_session_idx', table_name='radacct')
    op.drop_table('radacct')
    op.drop_index(op.f('ix_nasport_username'), table_name='nasport')
    op.drop_table('nasport')
    op.drop_index(op.f('ix_group_name'), table_name='group')
    op.drop_index(op.f('ix_group_id'), table_name='group')
    op.drop_table('group')
    op.drop_index(op.f('ix_assignment_rule_priority'), table_name='assignment_rule')
    op.drop_table('assignment_rule')
    # ### end Alembic commands ###
