"""nac_tables

Revision ID: d477fdb553ab
Revises:
Create Date: 2026-03-30 11:04:16.948738

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d477fdb553ab"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "endpoint_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "name", sa.Text(), server_default=sa.text("''::text"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_endpoint_group_name"), "endpoint_group", ["name"], unique=False
    )
    op.create_table(
        "group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("allowed_group_ids", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_group_id"), "group", ["id"], unique=False)
    op.create_index(op.f("ix_group_name"), "group", ["name"], unique=True)
    op.create_table(
        "nas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("network", postgresql.CIDR(), nullable=False),
        sa.Column(
            "type", sa.Text(), server_default=sa.text("'other'::text"), nullable=False
        ),
        sa.Column("secret", sa.Text(), nullable=False),
        sa.Column("server", sa.Text(), nullable=True),
        sa.Column(
            "require_ma",
            sa.Text(),
            server_default=sa.text("'auto'::text"),
            nullable=False,
        ),
        sa.Column(
            "limit_proxy_state",
            sa.Text(),
            server_default=sa.text("'auto'::text"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="nas_pkey"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_nas_id"), "nas", ["id"], unique=False)
    op.create_index(op.f("ix_nas_network"), "nas", ["network"], unique=True)
    op.create_table(
        "nasport",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.Unicode(length=64), nullable=False),
        sa.Column("calling_station_id", sa.Unicode(length=64), nullable=False),
        sa.Column("nas_identifier", sa.Unicode(length=64), nullable=False),
        sa.Column("nas_port_id", sa.Unicode(length=64), nullable=False),
        sa.Column("nas_ip_address", sa.Unicode(length=64), nullable=False),
        sa.Column("called_station_id", sa.Unicode(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint(
            "username",
            "calling_station_id",
            "called_station_id",
            "nas_port_id",
            name="uq_user_called_station_port",
        ),
        sa.UniqueConstraint(
            "username", "calling_station_id", "nas_identifier", "nas_port_id"
        ),
    )
    op.create_index(op.f("ix_nasport_id"), "nasport", ["id"], unique=False)
    op.create_index(
        "ix_nasport_username_calling_station_id",
        "nasport",
        ["username", "calling_station_id"],
        unique=False,
    )
    op.create_table(
        "nasreload",
        sa.Column("nasipaddress", postgresql.INET(), nullable=False),
        sa.Column("reloadtime", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("nasipaddress", name="nasreload_pkey"),
    )
    op.create_table(
        "policy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "port_locking",
            sa.Enum("SWITCH_PORT", "SWITCH", name="portlocking"),
            nullable=True,
        ),
        sa.Column(
            "client_type", sa.Enum("MAB", "EAP", name="clienttype"), nullable=True
        ),
        sa.Column(
            "port_type", sa.Enum("WIRED", "WIRELESS", name="porttype"), nullable=True
        ),
        sa.Column(
            "match_logic", sa.Enum("AND", "OR", name="matchlogic"), nullable=False
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_policy_id"), "policy", ["id"], unique=False)
    op.create_index(op.f("ix_policy_priority"), "policy", ["priority"], unique=False)
    op.create_table(
        "radacct",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("acct_session_id", sa.Text(), nullable=False),
        sa.Column("acct_unique_id", sa.Text(), nullable=False),
        sa.Column("nas_ip_address", postgresql.INET(), nullable=False),
        sa.Column("nas_identifier", sa.Text(), nullable=True),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("calling_station_id", sa.Text(), nullable=False),
        sa.Column("group_name", sa.Text(), nullable=True),
        sa.Column("realm", sa.Text(), nullable=True),
        sa.Column("nas_port_id", sa.Text(), nullable=True),
        sa.Column("nas_port_type", sa.Text(), nullable=True),
        sa.Column("acct_start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acct_update_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acct_stop_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acct_interval", sa.BigInteger(), nullable=True),
        sa.Column("acct_session_time", sa.BigInteger(), nullable=True),
        sa.Column("acct_authentic", sa.Text(), nullable=True),
        sa.Column("connectinfo_start", sa.Text(), nullable=True),
        sa.Column("connectinfo_stop", sa.Text(), nullable=True),
        sa.Column("acct_input_octets", sa.BigInteger(), nullable=True),
        sa.Column("acct_output_octets", sa.BigInteger(), nullable=True),
        sa.Column("called_station_id", sa.Text(), nullable=True),
        sa.Column("acct_terminate_cause", sa.Text(), nullable=True),
        sa.Column("service_type", sa.Text(), nullable=True),
        sa.Column("framed_protocol", sa.Text(), nullable=True),
        sa.Column("framed_ip_address", postgresql.INET(), nullable=True),
        sa.Column("framed_ipv6_address", postgresql.INET(), nullable=True),
        sa.Column("framed_ipv6_prefix", postgresql.INET(), nullable=True),
        sa.Column("framed_interface_id", sa.Text(), nullable=True),
        sa.Column("delegated_ipv6_prefix", postgresql.INET(), nullable=True),
        sa.Column("class", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("acct_unique_id"),
    )
    op.create_index(op.f("ix_radacct_id"), "radacct", ["id"], unique=False)
    op.create_index(
        "ix_radacct_username_calling_station_id",
        "radacct",
        ["username", "calling_station_id"],
        unique=False,
    )
    op.create_index(
        "radacct_active_session_idx", "radacct", ["acct_unique_id"], unique=False
    )
    op.create_index(
        "radacct_bulk_close",
        "radacct",
        ["nas_ip_address", "acct_start_time"],
        unique=False,
    )
    op.create_index(
        "radacct_bulk_timeout",
        "radacct",
        [sa.literal_column("acct_stop_time NULLS FIRST"), "acct_update_time"],
        unique=False,
    )
    op.create_index(
        "radacct_start_user_idx", "radacct", ["acct_start_time"], unique=False
    )
    op.create_table(
        "endpoint",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "username", sa.Text(), server_default=sa.text("''::text"), nullable=False
        ),
        sa.Column(
            "calling_station_id",
            sa.Text(),
            server_default=sa.text("''::text"),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "DISCOVERED", "REJECTED", "PENDING", "AUTHORIZED", name="endpointstate"
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["endpoint_group.id"], name="fk_endpoint_group_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username", "calling_station_id"),
    )
    op.create_index(op.f("ix_endpoint_id"), "endpoint", ["id"], unique=False)
    op.create_index(
        "ix_endpoint_username_calling_station_id",
        "endpoint",
        ["username", "calling_station_id"],
        unique=False,
    )
    op.create_table(
        "group_permission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("methods", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_group_permission_id"), "group_permission", ["id"], unique=False
    )
    op.create_table(
        "policy_condition",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("policy_id", sa.Integer(), nullable=False),
        sa.Column("attribute", sa.String(length=100), nullable=False),
        sa.Column(
            "operator",
            sa.Enum(
                "EQUALS",
                "NOT_EQUALS",
                "CONTAINS",
                "STARTS_WITH",
                "ENDS_WITH",
                "REGEX",
                "IN_LIST",
                name="conditionoperator",
            ),
            nullable=False,
        ),
        sa.Column("value_ref", sa.String(length=255), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(value_ref IS NOT NULL AND group_id IS NULL) OR (value_ref IS NULL AND group_id IS NOT NULL)",
            name="check_exclusive_reference",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["endpoint_group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policy.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_policy_condition_policy_id"),
        "policy_condition",
        ["policy_id"],
        unique=False,
    )
    op.create_table(
        "policy_reply",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("policy_id", sa.Integer(), nullable=False),
        sa.Column("attribute", sa.String(length=100), nullable=False),
        sa.Column(
            "operator",
            sa.Enum("EQUALS", "SET_EQUALS", name="replyoperator"),
            nullable=False,
        ),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policy.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_policy_reply_policy_id"), "policy_reply", ["policy_id"], unique=False
    )
    op.create_table(
        "radpostauth",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("calling_station_id", sa.Text(), nullable=False),
        sa.Column(
            "auth_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("pass", sa.Text(), nullable=True),
        sa.Column("reply", sa.Text(), nullable=True),
        sa.Column("called_station_id", sa.Text(), nullable=True),
        sa.Column("nas_ip_address", postgresql.INET(), nullable=False),
        sa.Column(
            "request_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("reply_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("matched_policy_id", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("nas_identifier", sa.Text(), nullable=True),
        sa.Column("nas_port_id", sa.Text(), nullable=True),
        sa.Column("class", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["matched_policy_id"], ["policy.id"], name="fk_policy_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_radpostauth_username_calling_station_id",
        "radpostauth",
        ["username", "calling_station_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_radpostauth_username_calling_station_id", table_name="radpostauth"
    )
    op.drop_table("radpostauth")
    op.drop_index(op.f("ix_policy_reply_policy_id"), table_name="policy_reply")
    op.drop_table("policy_reply")
    op.drop_index(op.f("ix_policy_condition_policy_id"), table_name="policy_condition")
    op.drop_table("policy_condition")
    op.drop_index(op.f("ix_group_permission_id"), table_name="group_permission")
    op.drop_table("group_permission")
    op.drop_index("ix_endpoint_username_calling_station_id", table_name="endpoint")
    op.drop_index(op.f("ix_endpoint_id"), table_name="endpoint")
    op.drop_table("endpoint")
    op.drop_index("radacct_start_user_idx", table_name="radacct")
    op.drop_index("radacct_bulk_timeout", table_name="radacct")
    op.drop_index("radacct_bulk_close", table_name="radacct")
    op.drop_index("radacct_active_session_idx", table_name="radacct")
    op.drop_index("ix_radacct_username_calling_station_id", table_name="radacct")
    op.drop_index(op.f("ix_radacct_id"), table_name="radacct")
    op.drop_table("radacct")
    op.drop_index(op.f("ix_policy_priority"), table_name="policy")
    op.drop_index(op.f("ix_policy_id"), table_name="policy")
    op.drop_table("policy")
    op.drop_table("nasreload")
    op.drop_index("ix_nasport_username_calling_station_id", table_name="nasport")
    op.drop_index(op.f("ix_nasport_id"), table_name="nasport")
    op.drop_table("nasport")
    op.drop_index(op.f("ix_nas_network"), table_name="nas")
    op.drop_index(op.f("ix_nas_id"), table_name="nas")
    op.drop_table("nas")
    op.drop_index(op.f("ix_group_name"), table_name="group")
    op.drop_index(op.f("ix_group_id"), table_name="group")
    op.drop_table("group")
    op.drop_index(op.f("ix_endpoint_group_name"), table_name="endpoint_group")
    op.drop_table("endpoint_group")
    # ### end Alembic commands ###
