"""nasport remove uniqueconstraint

Revision ID: 2ef2e1b87a3f
Revises: 03d35789fd6e
Create Date: 2026-03-03 10:50:59.989260

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "2ef2e1b87a3f"
down_revision = "03d35789fd6e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("nasport_username_calling_station_id_key"), "nasport", type_="unique"
    )
    op.create_unique_constraint(None, "nasport", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "nasport", type_="unique")
    op.create_unique_constraint(
        op.f("nasport_username_calling_station_id_key"),
        "nasport",
        ["username", "calling_station_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
