"""nas table

Revision ID: 296b4a1fd08a
Revises: c94eef4c3688
Create Date: 2026-03-13 10:35:57.910796

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "296b4a1fd08a"
down_revision = "c94eef4c3688"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("network", postgresql.CIDR(), nullable=False),
        sa.Column(
            "type", sa.Text(), server_default=sa.text("'other'::text"), nullable=False
        ),
        sa.Column("secret", sa.Text(), nullable=False),
        sa.Column(
            "require_ma",
            sa.Text(),
            server_default=sa.text("'auto'::text"),
            nullable=False,
        ),
        sa.Column(
            "limit_proxy_state",
            sa.Text(),
            server_default=sa.text("'auto'::text"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="nas_pkey"),
    )
    op.create_index(op.f("ix_nas_network"), "nas", ["network"], unique=False)
    op.create_table(
        "nasreload",
        sa.Column("nasipaddress", postgresql.INET(), nullable=False),
        sa.Column("reloadtime", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("nasipaddress", name="nasreload_pkey"),
    )
    op.add_column("group", sa.Column("allowed_groups", sa.JSON(), nullable=False))
    op.drop_column("group", "allowed_vlans")
    op.create_unique_constraint(None, "nasport", ["id"])
    op.drop_constraint(op.f("policy_description_key"), "policy", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("policy_description_key"),
        "policy",
        ["description"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(None, "nasport", type_="unique")
    op.add_column(
        "group",
        sa.Column(
            "allowed_vlans",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("group", "allowed_groups")
    op.drop_table("nasreload")
    op.drop_index(op.f("ix_nas_network"), table_name="nas")
    op.drop_table("nas")
    # ### end Alembic commands ###
