"""username_calling_index

Revision ID: 37c3ad9aea06
Revises: 2f8329a10a9e
Create Date: 2026-03-18 08:16:40.978339

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "37c3ad9aea06"
down_revision = "2f8329a10a9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_endpoint_calling_station_id"), table_name="endpoint")
    op.drop_index(op.f("ix_endpoint_username"), table_name="endpoint")
    op.create_index(
        "ix_endpoint_username_calling_station_id",
        "endpoint",
        ["username", "calling_station_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_nasport_calling_station_id"), table_name="nasport")
    op.drop_index(op.f("ix_nasport_username"), table_name="nasport")
    op.create_index(
        "ix_nasport_username_calling_station_id",
        "nasport",
        ["username", "calling_station_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_radacct_calling_station_id"), table_name="radacct")
    op.drop_index(op.f("ix_radacct_username"), table_name="radacct")
    op.create_index(
        "ix_radacct_username_calling_station_id",
        "radacct",
        ["username", "calling_station_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_radpostauth_calling_station_id"), table_name="radpostauth")
    op.drop_index(op.f("ix_radpostauth_username"), table_name="radpostauth")
    op.create_index(
        "ix_radpostauth_username_calling_station_id",
        "radpostauth",
        ["username", "calling_station_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_radpostauth_username_calling_station_id", table_name="radpostauth"
    )
    op.create_index(
        op.f("ix_radpostauth_username"), "radpostauth", ["username"], unique=False
    )
    op.create_index(
        op.f("ix_radpostauth_calling_station_id"),
        "radpostauth",
        ["calling_station_id"],
        unique=False,
    )
    op.drop_index("ix_radacct_username_calling_station_id", table_name="radacct")
    op.create_index(op.f("ix_radacct_username"), "radacct", ["username"], unique=False)
    op.create_index(
        op.f("ix_radacct_calling_station_id"),
        "radacct",
        ["calling_station_id"],
        unique=False,
    )
    op.drop_index("ix_nasport_username_calling_station_id", table_name="nasport")
    op.create_index(op.f("ix_nasport_username"), "nasport", ["username"], unique=False)
    op.create_index(
        op.f("ix_nasport_calling_station_id"),
        "nasport",
        ["calling_station_id"],
        unique=False,
    )
    op.drop_index("ix_endpoint_username_calling_station_id", table_name="endpoint")
    op.create_index(
        op.f("ix_endpoint_username"), "endpoint", ["username"], unique=False
    )
    op.create_index(
        op.f("ix_endpoint_calling_station_id"),
        "endpoint",
        ["calling_station_id"],
        unique=False,
    )
    # ### end Alembic commands ###
