"""nac tables

Revision ID: 9bd5e17aac9c
Revises: 54c12ecbea91
Create Date: 2026-02-18 08:54:57.586672

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9bd5e17aac9c"
down_revision = "54c12ecbea91"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_oui",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("oui", sa.Unicode(length=64), nullable=False),
        sa.Column("vlan", sa.Integer(), nullable=False),
        sa.Column("description", sa.Unicode(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("oui"),
    )
    op.create_index(op.f("ix_device_oui_id"), "device_oui", ["id"], unique=False)
    op.create_table(
        "nasport",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.Unicode(length=64), nullable=False),
        sa.Column("nas_identifier", sa.Unicode(length=64), nullable=False),
        sa.Column("nas_port_id", sa.Unicode(length=64), nullable=False),
        sa.Column("nas_ip_address", sa.Unicode(length=64), nullable=False),
        sa.Column("calling_station_id", sa.Unicode(length=64), nullable=False),
        sa.Column("called_station_id", sa.Unicode(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint(
            "username",
            "calling_station_id",
            "nas_port_id",
            name="uq_user_calling_station_port",
        ),
        sa.UniqueConstraint(
            "username", "nas_identifier", "nas_port_id", name="uq_user_nas_port"
        ),
    )
    op.create_index(op.f("ix_nasport_username"), "nasport", ["username"], unique=False)
    op.add_column("radacct", sa.Column("nasidentifier", sa.Text(), nullable=True))
    op.add_column(
        "radcheck",
        sa.Column(
            "enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "radcheck",
        sa.Column(
            "comment", sa.Text(), server_default=sa.text("''::text"), nullable=True
        ),
    )
    op.add_column(
        "radcheck", sa.Column("access_start", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "radcheck", sa.Column("access_stop", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "radcheck",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "radcheck",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_index(op.f("radcheck_username"), table_name="radcheck")
    op.create_unique_constraint("uq_username", "radcheck", ["username"])
    op.drop_column("radcheck", "op")
    op.drop_column("radcheck", "attribute")
    op.drop_column("radcheck", "value")
    op.add_column("radpostauth", sa.Column("reply_message", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("radpostauth", "reply_message")
    op.add_column(
        "radcheck",
        sa.Column(
            "value",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "radcheck",
        sa.Column(
            "attribute",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "radcheck",
        sa.Column(
            "op",
            sa.VARCHAR(length=2),
            server_default=sa.text("'=='::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint("uq_username", "radcheck", type_="unique")
    op.create_index(
        op.f("radcheck_username"), "radcheck", ["username", "attribute"], unique=False
    )
    op.drop_column("radcheck", "updated_at")
    op.drop_column("radcheck", "created_at")
    op.drop_column("radcheck", "access_stop")
    op.drop_column("radcheck", "access_start")
    op.drop_column("radcheck", "comment")
    op.drop_column("radcheck", "enabled")
    op.drop_column("radacct", "nasidentifier")
    op.drop_index(op.f("ix_nasport_username"), table_name="nasport")
    op.drop_table("nasport")
    op.drop_index(op.f("ix_device_oui_id"), table_name="device_oui")
    op.drop_table("device_oui")
    # ### end Alembic commands ###
