"""nac tables

Revision ID: ab7a249be816
Revises: 54c12ecbea91
Create Date: 2026-02-16 15:18:56.015612

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ab7a249be816"
down_revision = "54c12ecbea91"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_oui",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("oui", sa.Unicode(length=64), nullable=False),
        sa.Column("vlan", sa.Integer(), nullable=False),
        sa.Column("description", sa.Unicode(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("oui"),
    )
    op.create_index(op.f("ix_device_oui_id"), "device_oui", ["id"], unique=False)
    op.create_table(
        "nasport",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.Unicode(length=64), nullable=False),
        sa.Column("nas_identifier", sa.Unicode(length=64), nullable=False),
        sa.Column("nas_port_id", sa.Unicode(length=64), nullable=False),
        sa.Column("nas_ip_address", sa.Unicode(length=64), nullable=False),
        sa.Column("calling_station_id", sa.Unicode(length=64), nullable=False),
        sa.Column("called_station_id", sa.Unicode(length=64), nullable=False),
        sa.Column(
            "first_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_nasport_username"), "nasport", ["username"], unique=False)
    op.create_table(
        "raduserlog",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.Unicode(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACCEPT", "REJECT", "ERROR", name="authstatus"),
            nullable=False,
        ),
        sa.Column("reason", sa.Unicode(length=256), nullable=False),
        sa.Column("calling_station_id", sa.Unicode(length=64), nullable=False),
        sa.Column("nas_ip_address", sa.Unicode(length=64), nullable=False),
        sa.Column(
            "authdate",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_raduserlog_authdate"), "raduserlog", ["authdate"], unique=False
    )
    op.create_index(
        op.f("ix_raduserlog_calling_station_id"),
        "raduserlog",
        ["calling_station_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raduserlog_status"), "raduserlog", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_raduserlog_username"), "raduserlog", ["username"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_raduserlog_username"), table_name="raduserlog")
    op.drop_index(op.f("ix_raduserlog_status"), table_name="raduserlog")
    op.drop_index(op.f("ix_raduserlog_calling_station_id"), table_name="raduserlog")
    op.drop_index(op.f("ix_raduserlog_authdate"), table_name="raduserlog")
    op.drop_table("raduserlog")
    op.drop_index(op.f("ix_nasport_username"), table_name="nasport")
    op.drop_table("nasport")
    op.drop_index(op.f("ix_device_oui_id"), table_name="device_oui")
    op.drop_table("device_oui")
    # ### end Alembic commands ###
