"""rbac update

Revision ID: a63433c68e0d
Revises: d477fdb553ab
Create Date: 2026-04-18 15:52:24.758524

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a63433c68e0d"
down_revision = "d477fdb553ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rbac_endpoint_group_association",
        sa.Column("rbac_id", sa.Integer(), nullable=False),
        sa.Column("endpoint_group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["endpoint_group_id"],
            ["endpoint_group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rbac_id"],
            ["group.id"],
        ),
        sa.PrimaryKeyConstraint("rbac_id", "endpoint_group_id"),
    )
    op.create_table(
        "rbac_group_association",
        sa.Column("rbac_id", sa.Integer(), nullable=False),
        sa.Column("endpoint_group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["endpoint_group_id"], ["endpoint_group.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["rbac_id"], ["group.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("rbac_id", "endpoint_group_id"),
    )
    op.drop_column("group", "allowed_group_ids")
    op.create_unique_constraint(None, "nasport", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "nasport", type_="unique")
    op.add_column(
        "group",
        sa.Column(
            "allowed_group_ids",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_table("rbac_group_association")
    op.drop_table("rbac_endpoint_group_association")
    # ### end Alembic commands ###
