"""nac tables

Revision ID: b4172432a00b
Revises: 54c12ecbea91
Create Date: 2026-02-23 07:37:08.694414

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b4172432a00b"
down_revision = "54c12ecbea91"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_oui",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("oui", sa.Unicode(length=64), nullable=False),
        sa.Column("vlan", sa.Integer(), nullable=False),
        sa.Column("description", sa.Unicode(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("oui"),
    )
    op.create_index(op.f("ix_device_oui_id"), "device_oui", ["id"], unique=False)
    op.create_table(
        "group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("allowed_vlans", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_group_id"), "group", ["id"], unique=False)
    op.create_index(op.f("ix_group_name"), "group", ["name"], unique=True)
    op.create_table(
        "nasport",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.Unicode(length=64), nullable=False),
        sa.Column("nas_identifier", sa.Unicode(length=64), nullable=False),
        sa.Column("nas_port_id", sa.Unicode(length=64), nullable=False),
        sa.Column("nas_ip_address", sa.Unicode(length=64), nullable=False),
        sa.Column("calling_station_id", sa.Unicode(length=64), nullable=False),
        sa.Column("called_station_id", sa.Unicode(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint(
            "username",
            "calling_station_id",
            "nas_port_id",
            name="uq_user_calling_station_port",
        ),
        sa.UniqueConstraint(
            "username", "nas_identifier", "nas_port_id", name="uq_user_nas_port"
        ),
    )
    op.create_index(op.f("ix_nasport_username"), "nasport", ["username"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "username", sa.Text(), server_default=sa.text("''::text"), nullable=False
        ),
        sa.Column(
            "enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("vlan", sa.Integer(), nullable=False),
        sa.Column("access_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("access_stop", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="user_pkey"),
        sa.UniqueConstraint("username", name="uq_username"),
    )
    op.create_index("user_username", "user", ["username"], unique=False)
    op.create_table(
        "group_permission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("methods", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_group_permission_id"), "group_permission", ["id"], unique=False
    )
    op.add_column("radacct", sa.Column("nasidentifier", sa.Text(), nullable=True))
    op.add_column("radpostauth", sa.Column("reply_message", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("radpostauth", "reply_message")
    op.drop_column("radacct", "nasidentifier")
    op.drop_index(op.f("ix_group_permission_id"), table_name="group_permission")
    op.drop_table("group_permission")
    op.drop_index("user_username", table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_nasport_username"), table_name="nasport")
    op.drop_table("nasport")
    op.drop_index(op.f("ix_group_name"), table_name="group")
    op.drop_index(op.f("ix_group_id"), table_name="group")
    op.drop_table("group")
    op.drop_index(op.f("ix_device_oui_id"), table_name="device_oui")
    op.drop_table("device_oui")
    # ### end Alembic commands ###
