"""nac columns

Revision ID: 3079a5bd4495
Revises: 296b4a1fd08a
Create Date: 2026-03-13 13:30:16.730490

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3079a5bd4495"
down_revision = "296b4a1fd08a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "nas",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "nas",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_nas_network"), table_name="nas")
    op.create_index(op.f("ix_nas_network"), "nas", ["network"], unique=True)
    op.create_unique_constraint(None, "nas", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "nas", type_="unique")
    op.drop_index(op.f("ix_nas_network"), table_name="nas")
    op.create_index(op.f("ix_nas_network"), "nas", ["network"], unique=False)
    op.drop_column("nas", "updated_at")
    op.drop_column("nas", "created_at")
    # ### end Alembic commands ###
