"""postauth json columns

Revision ID: 610fe989fe4f
Revises: 37c3ad9aea06
Create Date: 2026-03-20 13:09:05.797642

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "610fe989fe4f"
down_revision = "37c3ad9aea06"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("group", sa.Column("allowed_group_ids", sa.JSON(), nullable=False))
    op.drop_column("group", "allowed_groups")
    op.add_column(
        "radpostauth",
        sa.Column(
            "request_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "radpostauth",
        sa.Column("reply_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("radpostauth", "reply_json")
    op.drop_column("radpostauth", "request_json")
    op.add_column(
        "group",
        sa.Column(
            "allowed_groups",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("group", "allowed_group_ids")
    # ### end Alembic commands ###
