"""rbac naming update

Revision ID: 78f51915d445
Revises: a63433c68e0d
Create Date: 2026-04-20 09:07:46.902194

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "78f51915d445"
down_revision = "a63433c68e0d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rbac",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rbac_id"), "rbac", ["id"], unique=False)
    op.create_index(op.f("ix_rbac_name"), "rbac", ["name"], unique=True)
    op.create_table(
        "rbac_permission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("resource", sa.String(), nullable=False),
        sa.Column("methods", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["rbac.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rbac_permission_id"), "rbac_permission", ["id"], unique=False
    )
    op.drop_index(op.f("ix_group_id"), table_name="group")
    op.drop_index(op.f("ix_group_name"), table_name="group")
    op.drop_table("rbac_group_association")
    op.drop_index(op.f("ix_group_permission_id"), table_name="group_permission")
    op.drop_table("group_permission")
    op.drop_constraint(
        op.f("rbac_endpoint_group_association_rbac_id_fkey"),
        "rbac_endpoint_group_association",
        type_="foreignkey",
    )
    op.drop_table("group")
    op.create_foreign_key(
        None, "rbac_endpoint_group_association", "rbac", ["rbac_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rbac_endpoint_group_association", type_="foreignkey")
    op.create_foreign_key(
        op.f("rbac_endpoint_group_association_rbac_id_fkey"),
        "rbac_endpoint_group_association",
        "group",
        ["rbac_id"],
        ["id"],
    )
    op.create_table(
        "group_permission",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("group_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("path", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "methods",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["group.id"], name=op.f("group_permission_group_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("group_permission_pkey")),
    )
    op.create_index(
        op.f("ix_group_permission_id"), "group_permission", ["id"], unique=False
    )
    op.create_table(
        "rbac_group_association",
        sa.Column("rbac_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "endpoint_group_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["endpoint_group_id"],
            ["endpoint_group.id"],
            name=op.f("rbac_group_association_endpoint_group_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rbac_id"],
            ["group.id"],
            name=op.f("rbac_group_association_rbac_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "rbac_id", "endpoint_group_id", name=op.f("rbac_group_association_pkey")
        ),
    )
    op.create_table(
        "group",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("group_pkey")),
    )
    op.create_index(op.f("ix_group_name"), "group", ["name"], unique=True)
    op.create_index(op.f("ix_group_id"), "group", ["id"], unique=False)
    op.drop_index(op.f("ix_rbac_permission_id"), table_name="rbac_permission")
    op.drop_table("rbac_permission")
    op.drop_index(op.f("ix_rbac_name"), table_name="rbac")
    op.drop_index(op.f("ix_rbac_id"), table_name="rbac")
    op.drop_table("rbac")
    # ### end Alembic commands ###
