"""ar tables

Revision ID: 8373002f15df
Revises: b4172432a00b
Create Date: 2026-02-23 08:26:01.287850

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8373002f15df"
down_revision = "b4172432a00b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assignment_rule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("target_vlan", sa.Integer(), nullable=False),
        sa.Column(
            "match_logic", sa.Enum("ALL", "ANY", name="matchlogic"), nullable=False
        ),
        sa.Column("reevaluate_existing", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_assignment_rule_priority"),
        "assignment_rule",
        ["priority"],
        unique=False,
    )
    op.create_table(
        "assignment_rule_condition",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rule_id", sa.Integer(), nullable=False),
        sa.Column("attribute", sa.String(length=100), nullable=False),
        sa.Column(
            "operator",
            sa.Enum(
                "EQUALS",
                "NOT_EQUALS",
                "CONTAINS",
                "STARTS_WITH",
                "ENDS_WITH",
                "REGEX",
                name="operator",
            ),
            nullable=False,
        ),
        sa.Column("target_value", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["assignment_rule.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_unique_constraint(None, "device_oui", ["id"])
    op.create_unique_constraint(None, "nasport", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "nasport", type_="unique")
    op.drop_constraint(None, "device_oui", type_="unique")
    op.drop_table("assignment_rule_condition")
    op.drop_index(op.f("ix_assignment_rule_priority"), table_name="assignment_rule")
    op.drop_table("assignment_rule")
    # ### end Alembic commands ###
