"""ar extension

Revision ID: 51e4a8354d66
Revises: 8373002f15df
Create Date: 2026-02-23 08:42:07.707177

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "51e4a8354d66"
down_revision = "8373002f15df"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE operator ADD VALUE 'IN_LIST'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
