"""postauth include nas_ip_address

Revision ID: 6013bd977ad4
Revises: 3079a5bd4495
Create Date: 2026-03-13 19:14:56.351643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6013bd977ad4'
down_revision = '3079a5bd4495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radpostauth', sa.Column('nas_ip_address', postgresql.INET(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radpostauth', 'nas_ip_address')
    # ### end Alembic commands ###
