"""nac coa fields

Revision ID: 99649d0cdb53
Revises: 78f51915d445
Create Date: 2026-05-07 06:38:48.313986

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "99649d0cdb53"
down_revision = "78f51915d445"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nas", sa.Column("coa_enabled", sa.Boolean(), nullable=False))
    op.add_column("nas", sa.Column("coa_port", sa.Integer(), nullable=True))
    op.add_column("nas", sa.Column("coa_secret", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nas", "coa_secret")
    op.drop_column("nas", "coa_port")
    op.drop_column("nas", "coa_enabled")
    # ### end Alembic commands ###
