"""remove reply operator

Revision ID: d5ae91c4bb60
Revises: 99649d0cdb53
Create Date: 2026-05-08 08:19:51.595297

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d5ae91c4bb60"
down_revision = "99649d0cdb53"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("policy_reply", "operator")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "policy_reply",
        sa.Column(
            "operator",
            postgresql.ENUM("EQUALS", "SET_EQUALS", name="replyoperator"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
