"""added radius admin event

Revision ID: 2ea6d68cfebe
Revises: d5ae91c4bb60
Create Date: 2026-07-14 09:02:36.265538

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2ea6d68cfebe"
down_revision = "d5ae91c4bb60"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "radius_admin_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "command",
            sa.Enum(
                "CLEAR_CLIENT",
                "DEBUG_START",
                "DEBUG_STOP",
                "DEBUG_CLEAR",
                name="radiuscommand",
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_radius_admin_event_id"), "radius_admin_event", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_radius_admin_event_id"), table_name="radius_admin_event")
    op.drop_table("radius_admin_event")
    # ### end Alembic commands ###
