"""nasport contraints

Revision ID: 44f0b38eb03e
Revises: dc8a3fb475b0
Create Date: 2026-02-18 07:43:48.641104

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "44f0b38eb03e"
down_revision = "dc8a3fb475b0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_user_calling_station_port",
        "nasport",
        ["username", "calling_station_id", "nas_port_id"],
    )
    op.create_unique_constraint(
        "uq_user_nas_port", "nasport", ["username", "nas_identifier", "nas_port_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_nas_port", "nasport", type_="unique")
    op.drop_constraint("uq_user_calling_station_port", "nasport", type_="unique")
    # ### end Alembic commands ###
