"""New fields

Revision ID: 4b50ec369159
Revises: 82183e6156c5
Create Date: 2026-02-17 18:38:16.315112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b50ec369159'
down_revision = '82183e6156c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radacct', sa.Column('nasidentifier', sa.Text(), nullable=True))
    op.add_column('radcheck', sa.Column('access_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('radcheck', sa.Column('access_stop', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radcheck', 'access_stop')
    op.drop_column('radcheck', 'access_start')
    op.drop_column('radacct', 'nasidentifier')
    # ### end Alembic commands ###
