"""nasidentifier radpostauth

Revision ID: 6d1dd883792c
Revises: 51e4a8354d66
Create Date: 2026-02-24 19:50:56.035771

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6d1dd883792c"
down_revision = "51e4a8354d66"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_device_oui_id"), table_name="device_oui")
    op.drop_table("device_oui")
    op.add_column("radpostauth", sa.Column("nasidentifier", sa.Text(), nullable=True))
    op.add_column("radpostauth", sa.Column("nasportid", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("radpostauth", "nasportid")
    op.drop_column("radpostauth", "nasidentifier")
    op.create_table(
        "device_oui",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("oui", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("vlan", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "description", sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("device_oui_pkey")),
        sa.UniqueConstraint(
            "id",
            name=op.f("device_oui_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "oui",
            name=op.f("device_oui_oui_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("ix_device_oui_id"), "device_oui", ["id"], unique=False)
    # ### end Alembic commands ###
