"""reply_message

Revision ID: 82183e6156c5
Revises: d1fcb845d28d
Create Date: 2026-02-17 13:18:10.349272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82183e6156c5'
down_revision = 'd1fcb845d28d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radpostauth', sa.Column('reply_message', sa.Text(), nullable=True))
    op.drop_column('radpostauth', 'reason')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radpostauth', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('radpostauth', 'reply_message')
    # ### end Alembic commands ###
