"""RadUserLog

Revision ID: 9c6110ddce3f
Revises: ab7a249be816
Create Date: 2026-02-17 12:53:15.352067

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9c6110ddce3f"
down_revision = "ab7a249be816"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "device_oui", ["id"])
    op.create_unique_constraint(None, "nasport", ["id"])
    op.alter_column(
        "raduserlog",
        "status",
        existing_type=postgresql.ENUM("ACCEPT", "REJECT", "ERROR", name="authstatus"),
        type_=sa.Unicode(length=64),
        existing_nullable=False,
    )
    op.create_unique_constraint(None, "raduserlog", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "raduserlog", type_="unique")
    op.alter_column(
        "raduserlog",
        "status",
        existing_type=sa.Unicode(length=64),
        type_=postgresql.ENUM("ACCEPT", "REJECT", "ERROR", name="authstatus"),
        existing_nullable=False,
    )
    op.drop_constraint(None, "nasport", type_="unique")
    op.drop_constraint(None, "device_oui", type_="unique")
    # ### end Alembic commands ###
