"""nas table virtual server

Revision ID: a347cdc0fff4
Revises: 6013bd977ad4
Create Date: 2026-03-16 11:11:13.858907

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a347cdc0fff4"
down_revision = "6013bd977ad4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nas", sa.Column("server", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nas", "server")
    # ### end Alembic commands ###
