"""added radius log table

Revision ID: a8cd81d56ccc
Revises: 2ea6d68cfebe
Create Date: 2026-07-15 10:58:07.272435

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a8cd81d56ccc"
down_revision = "2ea6d68cfebe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "radius_debug_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_name", sa.String(length=50), nullable=False),
        sa.Column("log_line", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_radius_debug_log_id"), "radius_debug_log", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_radius_debug_log_id"), table_name="radius_debug_log")
    op.drop_table("radius_debug_log")
    # ### end Alembic commands ###
