"""Remove RadUserLog

Revision ID: d1fcb845d28d
Revises: 9c6110ddce3f
Create Date: 2026-02-17 13:02:38.902929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1fcb845d28d'
down_revision = '9c6110ddce3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raduserlog_authdate'), table_name='raduserlog')
    op.drop_index(op.f('ix_raduserlog_calling_station_id'), table_name='raduserlog')
    op.drop_index(op.f('ix_raduserlog_status'), table_name='raduserlog')
    op.drop_index(op.f('ix_raduserlog_username'), table_name='raduserlog')
    op.drop_table('raduserlog')
    op.add_column('radpostauth', sa.Column('reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radpostauth', 'reason')
    op.create_table('raduserlog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('calling_station_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('nas_ip_address', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('authdate', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('raduserlog_pkey')),
    sa.UniqueConstraint('id', name=op.f('raduserlog_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_raduserlog_username'), 'raduserlog', ['username'], unique=False)
    op.create_index(op.f('ix_raduserlog_status'), 'raduserlog', ['status'], unique=False)
    op.create_index(op.f('ix_raduserlog_calling_station_id'), 'raduserlog', ['calling_station_id'], unique=False)
    op.create_index(op.f('ix_raduserlog_authdate'), 'raduserlog', ['authdate'], unique=False)
    # ### end Alembic commands ###
