"""Timestamps mixin

Revision ID: dc8a3fb475b0
Revises: 4b50ec369159
Create Date: 2026-02-18 07:09:41.978284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc8a3fb475b0'
down_revision = '4b50ec369159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nasport', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('nasport', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('nasport', 'last_seen')
    op.drop_column('nasport', 'first_seen')
    op.add_column('radcheck', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('radcheck', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radcheck', 'updated_at')
    op.drop_column('radcheck', 'created_at')
    op.add_column('nasport', sa.Column('first_seen', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('nasport', sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('nasport', 'updated_at')
    op.drop_column('nasport', 'created_at')
    # ### end Alembic commands ###
