"""created_at index

Revision ID: ddf93c94faa7
Revises: a8cd81d56ccc
Create Date: 2026-07-16 11:24:20.039321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf93c94faa7'
down_revision = 'a8cd81d56ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_endpoint_created_at'), 'endpoint', ['created_at'], unique=False)
    op.create_index(op.f('ix_endpoint_group_created_at'), 'endpoint_group', ['created_at'], unique=False)
    op.create_index(op.f('ix_nas_created_at'), 'nas', ['created_at'], unique=False)
    op.create_index(op.f('ix_nasport_created_at'), 'nasport', ['created_at'], unique=False)
    op.create_index(op.f('ix_policy_created_at'), 'policy', ['created_at'], unique=False)
    op.create_index(op.f('ix_radius_admin_event_created_at'), 'radius_admin_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_radius_debug_log_created_at'), 'radius_debug_log', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_radius_debug_log_created_at'), table_name='radius_debug_log')
    op.drop_index(op.f('ix_radius_admin_event_created_at'), table_name='radius_admin_event')
    op.drop_index(op.f('ix_policy_created_at'), table_name='policy')
    op.drop_index(op.f('ix_nasport_created_at'), table_name='nasport')
    op.drop_index(op.f('ix_nas_created_at'), table_name='nas')
    op.drop_index(op.f('ix_endpoint_group_created_at'), table_name='endpoint_group')
    op.drop_index(op.f('ix_endpoint_created_at'), table_name='endpoint')
    # ### end Alembic commands ###
