services:
  nac_api_external:
    build:
      context: ..
      dockerfile: docker/api/Dockerfile
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health').getcode()"]
      interval: 10s
      retries: 5
      start_period: 3s
      timeout: 10s
    ports:
      - 8000:8000
    environment:
      - RADIUS_SLAVE=no
      - RADIUS_COA_SECRET=testing123
      - RADIUS_NO_PORT_LOCK=no
      - RADIUS_DEFAULT_VLAN=13
      - POSTGRES_USER=cnaas
      - POSTGRES_PASSWORD=cnaas
    command: ["external"]
    depends_on:
      - nac_postgres

  nac_api_internal:
    build:
      context: ..
      dockerfile: docker/api/Dockerfile
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health').getcode()"]
      interval: 10s
      retries: 5
      start_period: 3s
      timeout: 10s
    expose:
      - 8000
    ports:
      - 8001:8000
    environment:
      - RADIUS_SLAVE=no
      - RADIUS_COA_SECRET=testing123
      - RADIUS_NO_PORT_LOCK=no
      - RADIUS_DEFAULT_VLAN=13
      - POSTGRES_USER=cnaas
      - POSTGRES_PASSWORD=cnaas
      # - POSTGRES_DB=nac
    command: ["internal"]
    depends_on:
      - nac_postgres

  nac_radius:
    build:
      context: ..
      dockerfile: docker/radius/Dockerfile
    ports:
      - 1812:1812/udp
      - 1813:1813/udp
    environment:
      - RADIUS_SERVER_SECRET=testing123
    command: ["-X"]
    depends_on:
      nac_api_internal:
        condition: service_healthy
        # restart: true
    volumes:
      - type: volume
        source: nac-freeradius-data
        target: /etc/Freeradius/3.0/
      - type: volume
        source: nac-var-data
        target: /var/
      - type: volume
        source: nac-api-certs
        target: /opt/cnaas/certs/

  nac_postgres:
    build: ./postgres
    restart: unless-stopped
    volumes:
      - type: volume
        source: nac-postgres-data
        target: /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cnaas
      - POSTGRES_PASSWORD=cnaas
      - POSTGRES_DB=nac
    ports:
      - 5432:5432

volumes:
  nac-postgres-data:
    external: false
  nac-freeradius-data:
    external: false
  nac-var-data:
    external: false
  nac-api-certs:
    external: false
