services:
  nac_api_external:
    build:
      context: ..
      dockerfile: docker/api/Dockerfile
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/v2/health').getcode()"]
      interval: 3s
      retries: 10
      start_period: 3s
      timeout: 10s
    ports:
      - 8000:8000
    environment:
      - RADIUS_COA_SECRET=testing123
      - POSTGRES_USER=cnaas
      - POSTGRES_PASSWORD=cnaas
      - ENVIRONMENT=local
      - LOGGING=debug
    command: ["external"]
    depends_on:
      nac_postgres:
        condition: service_healthy

  nac_api_internal:
    build:
      context: ..
      dockerfile: docker/api/Dockerfile
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/v2/health').getcode()"]
      interval: 3s
      retries: 10
      start_period: 3s
      timeout: 10s
    expose:
      - 8000
    ports:
      - 8001:8000 # For local testing
    environment:
      - POSTGRES_USER=cnaas
      - POSTGRES_PASSWORD=cnaas
      - LOGGING=debug
    command: ["internal"]
    depends_on:
      nac_postgres:
        condition: service_healthy
    # dns:
    #   - 192.168.0.1
    # dns_search: example.com

  nac_radius:
    build:
      context: ..
      dockerfile: docker/radius/Dockerfile
    restart: unless-stopped
    ports:
      - 1812:1812/udp
      - 1813:1813/udp
    environment:
      RADIUS_SERVER_SECRET: testing123
      RADIUS_EAP_CONFIGS: |
        [
            {
                "domain": "example.org",
                "private_key_password": "whatever",
                "cert": "",
                "ca": "",
                "check_crl": false,
                "crl_url": ""
            }
        ]
    # command: ["-X"]
    depends_on:
      nac_api_internal:
        condition: service_healthy
        # restart: true
    volumes:
      - type: volume
        source: nac-freeradius-certs
        target: /opt/etc/raddb/certs/
      - type: volume
        source: nac-freeradius-logs
        target: /opt/var/log/radius/
      - type: volume
        source: nac-freeradius-socket
        target: /opt/var/run/radiusd/
      - type: volume
        source: nac-api-certs
        target: /opt/cnaas/certs/
    # dns:
    #   - 192.168.0.1
    # dns_search: example.com

  nac_radmin:
    hostname: nac_radmin_1
    build:
      context: ..
      dockerfile: docker/radmin/Dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_USER=cnaas
      - POSTGRES_PASSWORD=cnaas
    depends_on:
      nac_postgres:
        condition: service_healthy
    volumes:
      - type: volume
        source: nac-freeradius-socket
        target: /var/run/radiusd/
      - type: volume
        source: nac-freeradius-logs
        target: /var/log/radius/

  nac_postgres:
    image: postgres:18
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - type: volume
        source: nac-postgres-data
        target: /var/lib/postgresql/18/docker
    environment:
      - POSTGRES_USER=cnaas
      - POSTGRES_PASSWORD=cnaas
      - POSTGRES_DB=nac
    ports:
      - 5432:5432

volumes:
  nac-postgres-data:
    external: false
  nac-freeradius-certs:
    external: false
  nac-var-data:
    external: false
  nac-freeradius-socket:
    external: false
  nac-freeradius-logs:
    external: false
  nac-api-certs:
    external: false

networks:
  default:
    ipam:
      config:
        - subnet: 10.100.1.0/24