client localhost {
    ipaddr = 127.0.0.1
    secret = testing123
}

client dockernet {
	ipaddr = 172.17.0.0/16
	secret = testing123
}


client net10net {
	ipaddr = 10.0.0.0/8
	secret = testing123
}


client switches {
	ipaddr = 10.105.0.0/16
	secret = testing123
}

client aps {
	ipaddr = 10.105.2.1/24
	secret = testing123
}