name: CNaaS NAC

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        
      - name: Install dependencies
        run: sudo apt install -y python3-pip docker-compose
        
      - name: Start PostgreSQL
        run: docker compose -f docker/docker-compose.dev.yml up -d nac_postgres

      - name: Install requirements
        run: |
          pip3 install .
          pip3 install --group dev

      - name: Run tests
        run: POSTGRES_SERVER=127.0.0.1 pytest
